import { FONT_OPTIONS } from "../../text-overlay/fonts";
import type { EffectDefinition } from "../types";

export const definition: EffectDefinition = {
	id: "caption",
	name: "Caption",
	moshable: false,
	params: [
		{
			key: "text",
			label: "Text",
			type: "text",
			defaultValue: "",
			maxLength: 120,
			placeholder: "Caption text",
		},
		{
			key: "x",
			label: "Position X",
			type: "range",
			min: 0,
			max: 1,
			step: 0.01,
			defaultValue: 0.5,
		},
		{
			key: "y",
			label: "Position Y",
			type: "range",
			min: 0,
			max: 1,
			step: 0.01,
			defaultValue: 0.5,
		},
		{
			key: "size",
			label: "Size",
			type: "range",
			min: 0.02,
			max: 0.5,
			step: 0.005,
			defaultValue: 0.1,
		},
		{
			key: "font",
			label: "Font",
			type: "select",
			fontPicker: true,
			defaultValue: FONT_OPTIONS[0].family,
			options: FONT_OPTIONS.map((f) => ({
				label: f.label,
				value: f.family,
			})),
		},
		{
			key: "align",
			label: "Align",
			type: "select",
			defaultValue: "center",
			options: [
				{ label: "Left", value: "left" },
				{ label: "Center", value: "center" },
				{ label: "Right", value: "right" },
			],
		},
		{
			key: "color",
			label: "Color",
			type: "color",
			defaultValue: "#ffffff",
		},
		{
			key: "outline",
			label: "Outline",
			type: "checkbox",
			defaultValue: 1,
		},
		{
			key: "outlineColor",
			label: "Outline Color",
			type: "color",
			defaultValue: "#000000",
			visibleWhen: (v) => v.outline === 1,
		},
		{
			key: "outlineWidth",
			label: "Outline Width",
			type: "range",
			min: 0,
			max: 8,
			step: 0.5,
			defaultValue: 2,
			visibleWhen: (v) => v.outline === 1,
		},
		{
			key: "opacity",
			label: "Opacity",
			type: "range",
			min: 0,
			max: 1,
			step: 0.01,
			defaultValue: 1,
		},
		{
			key: "blendMode",
			label: "Blend Mode",
			type: "select",
			defaultValue: "normal",
			options: [
				{ label: "Normal", value: "normal" },
				{ label: "Multiply", value: "multiply" },
				{ label: "Screen", value: "screen" },
				{ label: "Overlay", value: "overlay" },
				{ label: "Add", value: "add" },
				{ label: "Subtract", value: "subtract" },
				{ label: "Difference", value: "difference" },
				{ label: "Exclusion", value: "exclusion" },
			],
		},
	],
};
