export { createMediaHistory } from "./history.svelte";
export {
	applyBpmToMediaClips,
	clearMediaClips,
	dealMediaClipSources,
	fillMediaClipsFromPreset,
	restoreMediaClipMosh,
	rollMediaClips,
	setMediaClipsMode,
	syncMediaClipsToPreset,
} from "./chain";
export type { MediaClipboardEntry, MediaPasteResult } from "./clipboard";
export {
	copyMediaClips,
	pasteMediaClips,
	pasteMediaContentOnto,
} from "./clipboard";
export type {
	AnimatedKey,
	ChromaKey,
	CropRect,
	Keyframe,
	MaskKey,
	MaskTransform,
	SourceEdit,
	SourceEditAnim,
	SourceSpan,
} from "./source-edit";
export {
	clampCrop,
	createSourceEdit,
	cropExtent,
	DEFAULT_CHROMA_KEY,
	DEFAULT_SOURCE_EDIT,
	FULL_CROP,
	hasAnimation,
	IDENTITY_MASK_TRANSFORM,
	isFullCrop,
	isIdleSourceEdit,
	KEY_EPSILON,
	KEY_NEAR,
	keyCoverage,
	keyframeAt,
	MASK_MAX,
	normalizeSourceEdit,
	normalizeSourceEdits,
	putKeyframe,
	removeKeyframe,
	sampleSourceEdit,
	sampleTrack,
	wrapSourceTime,
	clampSpan,
	sourcePlayLength,
	sourceSpan,
	sourceSpeed,
	sourceTimeAt,
	SPAN_MIN,
	SPEED_MIN,
	SPEED_MAX,
} from "./source-edit";
export type { MediaChainSource, ResolvedMediaLayer } from "./resolve";
export {
	addClip,
	allMediaEffectIds,
	createMediaChainSource,
	clipAt,
	clipRange,
	clipSourceId,
	detachMediaSource,
	findMediaClip,
	findMediaClipIn,
	findMediaClipLane,
	freeRangeAt,
	laneSourceIds,
	mediaTimelineSourceIds,
	moveClip,
	moveClips,
	moveClipsToLane,
	newClipSpan,
	removeClip,
	replaceMediaClip,
	resizeBoundary,
	resizeClip,
	resolveMediaLayersAt,
	setMediaClipSources,
	sortClips,
	updateMediaClips,
	updateMediaLane,
} from "./resolve";
export type {
	MediaClip,
	MediaFit,
	MediaLane,
	MediaStyle,
	MediaTimeline,
} from "./types";
export {
	appendMediaLane,
	createMediaClip,
	createMediaLane,
	createMediaTimeline,
	DEFAULT_MEDIA_STYLE,
	EMPTY_MEDIA_TIMELINE,
	fitMediaTimeline,
	MAX_MEDIA_LANES,
	MEDIA_FIT_OPTIONS,
	mediaClipWeight,
	MIN_CLIP_LENGTH,
	normalizeMediaTimeline,
	splitMediaClipAt,
} from "./types";
