import { FONT_OPTIONS } from '../text-overlay/fonts';
import type { EffectDefinition } from './types';

/**
 * ASCII effect character sets. Length is free and order doesn't matter — the
 * atlas sorts each set by the ink each glyph actually rasterizes to, so these
 * are pools, not hand-ordered ramps. Repeats bias the ramp: 'binary' is mostly
 * spaces, so it thresholds hard instead of shading.
 */
export const ASCII_CHARSETS: { label: string; value: string; chars: string }[] = [
   { label: 'Classic', value: 'classic', chars: ' .:-=+*#%@' },
   {
      label: 'Detailed',
      value: 'detailed',
      chars:
         " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$",
   },
   { label: 'Blocks', value: 'blocks', chars: ' ░▒▓█' },
   { label: 'Binary', value: 'binary', chars: '        00001111' },
   { label: 'Numbers', value: 'numbers', chars: ' .-:;17245308#%@' },
];

export const EFFECT_DEFINITIONS: EffectDefinition[] = [
   {
      id: 'pixelate',
      name: 'Pixelate',
      params: [
         {
            key: 'size',
            label: 'Size',
            type: 'range',
            min: 1,
            max: 100,
            step: 1,
            defaultValue: 10,
         },
      ],
   },
   {
      id: 'posterize',
      name: 'Posterize',
      params: [
         {
            key: 'levels',
            label: 'Levels',
            type: 'range',
            min: 2,
            max: 20,
            step: 1,
            defaultValue: 8,
         },
      ],
   },
   {
      id: 'solarize',
      name: 'Solarize',
      params: [
         {
            key: 'pivot',
            label: 'Pivot',
            type: 'range',
            min: 0.1,
            max: 0.9,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'curve',
            label: 'Curve',
            type: 'range',
            min: 0.5,
            max: 4,
            step: 0.05,
            defaultValue: 2,
         },
         {
            key: 'colorize',
            label: 'Colorize',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.1,
            // The classic look sits near the bottom of the range; moshing to
            // 0.8 just makes a hue-shifted negative.
            moshMax: 0.4,
         },
      ],
   },
   {
      id: 'edges',
      name: 'Edges',
      params: [
         {
            key: 'strength',
            label: 'Strength',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'mix',
            label: 'Mix',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'neon-edges',
      name: 'Neon Edges',
      params: [
         {
            key: 'strength',
            label: 'Strength',
            type: 'range',
            min: 0.1,
            max: 5.0,
            step: 0.1,
            defaultValue: 1.5,
         },
         {
            key: 'glow',
            label: 'Glow',
            type: 'range',
            min: 0.0,
            max: 3.0,
            step: 0.05,
            defaultValue: 1.0,
         },
         {
            key: 'bg',
            label: 'Background',
            type: 'range',
            min: 0.0,
            max: 1.0,
            step: 0.01,
            defaultValue: 0.05,
         },
      ],
   },
   {
      id: 'bleach',
      name: 'Bleach',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'sharpen',
      name: 'Sharpen',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 10,
            step: 0.01,
            defaultValue: 3,
         },
         {
            key: 'radius',
            label: 'Radius',
            type: 'range',
            min: 0.5,
            max: 25,
            step: 0.5,
            defaultValue: 5,
         },
         {
            key: 'threshold',
            label: 'Threshold',
            type: 'range',
            min: 0,
            max: 0.25,
            step: 0.005,
            defaultValue: 0,
         },
      ],
   },
   {
      id: 'mirror',
      name: 'Mirror',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'side',
            label: 'Side',
            type: 'range',
            min: 0,
            max: 3,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'position',
            label: 'Position',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'kaleido',
      name: 'Kaleido',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'sides',
            label: 'Sides',
            type: 'range',
            min: 2,
            max: 12,
            step: 1,
            defaultValue: 6,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
      ],
   },
   {
      id: 'channel-split',
      name: 'Channel Split',
      params: [
         {
            key: 'mode',
            label: 'Mode',
            type: 'select',
            defaultValue: 'linear',
            options: [
               { label: 'Linear', value: 'linear' },
               { label: 'Radial', value: 'radial' },
               { label: 'Prismatic', value: 'prismatic' },
            ],
         },
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 50,
            step: 0.1,
            defaultValue: 10,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
            visibleWhen: (v) => v.mode === 'linear' || v.mode === 'prismatic',
         },
         {
            key: 'falloff',
            label: 'Falloff',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
            visibleWhen: (v) => v.mode === 'radial',
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0,
            max: 5,
            step: 0.1,
            defaultValue: 1,
            visibleWhen: (v) => v.mode === 'prismatic',
         },
         {
            key: 'saturation',
            label: 'Hue Shift',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
            visibleWhen: (v) => v.mode === 'prismatic',
         },
      ],
   },
   {
      id: 'color-correction',
      name: 'Color Correction',
      params: [
         {
            key: 'brightness',
            label: 'Brightness',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            defaultValue: 0,
            moshMin: -0.5,
         },
         {
            key: 'contrast',
            label: 'Contrast',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            moshMin: -0.5,
            moshMax: 0.5,
            defaultValue: 0,
         },
         {
            key: 'hue',
            label: 'Hue',
            type: 'range',
            min: -180,
            max: 180,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'saturation',
            label: 'Saturation',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            defaultValue: 0,
         },
      ],
   },
   {
      id: 'vignette',
      name: 'Vignette',
      params: [
         {
            key: 'size',
            label: 'Size',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'scanlines',
      name: 'Scanlines',
      params: [
         {
            key: 'count',
            label: 'Count',
            type: 'range',
            min: 1,
            max: 500,
            step: 1,
            defaultValue: 100,
         },
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'bulge',
      name: 'Bulge',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'radius',
            label: 'Radius',
            type: 'range',
            min: 0.01,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'jitter',
      name: 'Jitter',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 100,
            step: 1,
            defaultValue: 20,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'wobble',
      name: 'Wobble',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 100,
            step: 1,
            defaultValue: 20,
         },
         {
            key: 'frequency',
            label: 'Frequency',
            type: 'range',
            min: 1,
            max: 5,
            step: 0.1,
            defaultValue: 3,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'slices',
      name: 'Slices',
      params: [
         {
            key: 'count',
            label: 'Count',
            type: 'range',
            min: 1,
            max: 50,
            step: 1,
            defaultValue: 10,
         },
         {
            key: 'offset',
            label: 'Offset',
            type: 'range',
            min: 0,
            max: 100,
            step: 1,
            defaultValue: 20,
         },
         {
            key: 'direction',
            label: 'Direction',
            type: 'select',
            defaultValue: 'horizontal',
            options: [
               { label: 'Horizontal', value: 'horizontal' },
               { label: 'Vertical', value: 'vertical' },
            ],
         },
      ],
   },
   {
      id: 'shake',
      name: 'Shake',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 50,
            step: 1,
            defaultValue: 10,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 1,
            max: 60,
            step: 1,
            defaultValue: 20,
            curve: 5,
         },
      ],
   },
   {
      id: 'glow',
      name: 'Glow',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 50,
            step: 0.01,
            defaultValue: 4,
         },
         {
            key: 'cutoff',
            label: 'Cutoff',
            type: 'range',
            min: 0,
            max: 0.7,
            step: 0.01,
            defaultValue: 0.3,
         },
         {
            key: 'radius',
            label: 'Radius',
            type: 'range',
            min: 1,
            max: 10,
            step: 0.5,
            defaultValue: 8,
         },
      ],
   },
   {
      id: 'soft-glitch',
      name: 'Glitch',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 50,
            step: 1,
            defaultValue: 15,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 2,
         },
      ],
   },
   {
      id: 'optical-flow',
      name: 'Optical Flow',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.65,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 10,
            step: 0.1,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'vhs',
      name: 'VHS',
      params: [
         {
            key: 'static',
            label: 'Static',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 1,
         },
         {
            key: 'tracking',
            label: 'Tracking',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'duotone',
      name: 'Duotone',
      params: [
         {
            key: 'shadowColor',
            label: 'Shadow',
            type: 'color',
            defaultValue: '#00194d',
         },
         {
            key: 'highlightColor',
            label: 'Highlight',
            type: 'color',
            defaultValue: '#ffaa00',
         },
         {
            key: 'intensity',
            label: 'Intensity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'grain',
      name: 'Grain',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
         },
         { key: 'rgb', label: 'RGB', type: 'checkbox', defaultValue: 1 },
         {
            key: 'blendMode',
            label: 'Blend Mode',
            type: 'select',
            defaultValue: 'additive',
            options: [
               { label: 'Additive', value: 'additive' },
               { label: 'Softlight', value: 'softlight' },
               { label: 'Multiply', value: 'multiply' },
            ],
         },
      ],
   },
   {
      id: 'polar',
      name: 'Polar',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
      ],
   },
   {
      id: 'tile',
      name: 'Tile',
      params: [
         {
            key: 'size',
            label: 'Size',
            type: 'range',
            min: 1,
            max: 10,
            step: 0.1,
            defaultValue: 2,
         },
         {
            key: 'offset',
            label: 'Offset',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0,
            max: 50,
            step: 0.1,
            defaultValue: 0,
            moshMax: 20
         },
      ],
   },
   {
      id: 'data-bend',
      name: 'Data Bend',
      params: [
         {
            key: 'intensity',
            label: 'Intensity',
            type: 'range',
            min: 0,
            max: 100,
            step: 1,
            defaultValue: 30,
         },
         {
            key: 'corruption',
            label: 'Corruption',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
         },
         {
            key: 'channelShift',
            label: 'Channel Shift',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.2,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.5,
            max: 20,
            step: 0.5,
            defaultValue: 4,
         },
      ],
   },
   {
      id: 'melt',
      name: 'Melt',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'emboss',
      name: 'Emboss',
      params: [
         {
            key: 'strength',
            label: 'Strength',
            type: 'range',
            min: 0,
            max: 5,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 135,
         },
         {
            key: 'mix',
            label: 'Mix',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'thermal',
      name: 'Thermal',
      params: [
         {
            key: 'intensity',
            label: 'Intensity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'palette',
            label: 'Palette',
            type: 'select',
            defaultValue: 'thermal',
            options: [
               { label: 'Thermal', value: 'thermal' },
               { label: 'Infrared', value: 'infrared' },
               { label: 'Night Vision', value: 'night-vision' },
            ],
         },
      ],
   },
   {
      id: 'color-halves',
      name: 'Color Halves',
      params: [
         {
            key: 'position',
            label: 'Position',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'mode',
            label: 'Mode',
            type: 'select',
            defaultValue: 'invert',
            options: [
               { label: 'Invert', value: 'invert' },
               { label: 'Hue Shift', value: 'hue-shift' },
               { label: 'Desaturate', value: 'desaturate' },
               { label: 'High Contrast', value: 'high-contrast' },
            ],
         },
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'stereoscopic',
      name: 'Stereoscopic',
      params: [
         {
            key: 'depth',
            label: 'Depth',
            type: 'range',
            min: 0,
            max: 50,
            step: 1,
            defaultValue: 10,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'mode',
            label: 'Mode',
            type: 'select',
            defaultValue: 'anaglyph',
            options: [
               { label: 'Anaglyph', value: 'anaglyph' },
               { label: 'Color Split', value: 'color-split' },
            ],
         },
         {
            key: 'depthSource',
            label: 'Depth Source',
            type: 'select',
            defaultValue: 'luminance',
            options: [
               { label: 'Luminance', value: 'luminance' },
               { label: 'Edges', value: 'edges' },
               { label: 'Flat', value: 'flat' },
            ],
         },
         {
            key: 'focus',
            label: 'Focus',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'pixel-sort',
      name: 'Pixel Sort',
      params: [
         {
            key: 'threshold',
            label: 'Threshold',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'ceiling',
            label: 'Ceiling',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'range',
            label: 'Range',
            type: 'range',
            min: 0,
            max: 200,
            step: 1,
            defaultValue: 80,
         },
         {
            key: 'direction',
            label: 'Direction',
            type: 'select',
            defaultValue: 'horizontal',
            options: [
               { label: 'Horizontal', value: 'horizontal' },
               { label: 'Vertical', value: 'vertical' },
            ],
         },
         { key: 'reverse', label: 'Reverse', type: 'checkbox', defaultValue: 0 },
      ],
   },
   {
      id: 'smear',
      name: 'Smear',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'trail',
            label: 'Trail',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
         },
      ],
   },
   {
      id: 'fiber-displace',
      name: 'Fiber Displace',
      params: [
         {
            key: 'strength',
            label: 'Strength',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
         {
            key: 'density',
            label: 'Stripe Density',
            type: 'range',
            min: 2,
            max: 50,
            step: 1,
            defaultValue: 30,
         },
         {
            key: 'chrome',
            label: 'Colorize',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'smoothness',
            label: 'Smoothness',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
         },
      ],
   },
   {
      id: 'relief',
      name: 'Relief',
      params: [
         {
            key: 'amount',
            label: 'Depth',
            type: 'range',
            min: 0,
            max: 0.8,
            step: 0.005,
            defaultValue: 0.35,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 360,
            step: 1,
            defaultValue: 30,
         },
      ],
   },
   {
      id: 'zoom',
      name: 'Zoom',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            defaultValue: 0,
         },
      ],
   },
   {
      id: 'tunnel',
      name: 'Tunnel',
      params: [
         {
            key: 'zoom',
            label: 'Zoom',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
         },
         {
            key: 'spin',
            label: 'Spin',
            type: 'range',
            min: -180,
            max: 180,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'decay',
            label: 'Decay',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.2,
         },
      ],
   },
   {
      id: 'audio-bars',
      name: 'Audio Bars',
      params: [
         {
            key: 'bars',
            label: 'Bars',
            type: 'range',
            min: 8,
            max: 128,
            step: 1,
            defaultValue: 48,
         },
         {
            key: 'height',
            label: 'Height',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
         {
            key: 'gain',
            label: 'Gain',
            type: 'range',
            min: 0.1,
            max: 3,
            step: 0.05,
            // 1.0 now that the bins arrive normalized: anything above it just
            // clips the peaks flat against the top of the bar.
            defaultValue: 1,
         },
         {
            // Both default to DEFAULT_AUDIO_RESPONSE, so the bars start out
            // following the music the same way a volume link does.
            key: 'smoothing',
            label: 'Smoothing',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
         },
         {
            key: 'punch',
            label: 'Punch',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
         {
            key: 'opacity',
            label: 'Opacity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.9,
         },
         {
            key: 'anchor',
            label: 'Anchor',
            type: 'select',
            defaultValue: 'bottom',
            options: [
               { label: 'Bottom', value: 'bottom' },
               { label: 'Top', value: 'top' },
               { label: 'Center', value: 'center' },
            ],
         },
         {
            key: 'style',
            label: 'Style',
            type: 'select',
            defaultValue: 'solid',
            options: [
               { label: 'Solid', value: 'solid' },
               { label: 'Segmented', value: 'segmented' },
            ],
         },
         {
            key: 'color',
            label: 'Color',
            type: 'color',
            defaultValue: '#4dffb8',
         },
      ],
   },
   {
      id: 'strobe',
      name: 'Strobe',
      params: [
         {
            // Keyed "speed" so the renderer accumulates phase for it: one unit
            // of phase is one flash, making this literally flashes per second.
            key: 'speed',
            label: 'Rate',
            type: 'range',
            min: 0.2,
            max: 20,
            step: 0.1,
            defaultValue: 5,
         },
         {
            key: 'duty',
            label: 'Duty',
            type: 'range',
            min: 0.05,
            max: 0.95,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'mode',
            label: 'Mode',
            type: 'select',
            defaultValue: 'black',
            options: [
               { label: 'Blackout', value: 'black' },
               { label: 'Whiteout', value: 'white' },
               { label: 'Invert', value: 'invert' },
               { label: 'Mono', value: 'mono' },
            ],
         },
      ],
   },
   {
      id: 'feedback',
      name: 'Feedback',
      params: [
         {
            key: 'decay',
            label: 'Decay',
            type: 'range',
            // Never quite 0: with no decay the loop never releases a frame and
            // the image welds itself to whatever was brightest.
            min: 0.02,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
         },
         {
            key: 'scale',
            label: 'Scale',
            type: 'range',
            min: -1,
            max: 1,
            step: 0.01,
            defaultValue: 0.12,
         },
         {
            key: 'rotate',
            label: 'Rotate',
            type: 'range',
            min: -90,
            max: 90,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'warp',
            label: 'Warp',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0,
         },
         {
            key: 'hue',
            label: 'Hue Shift',
            type: 'range',
            min: -180,
            max: 180,
            step: 1,
            defaultValue: 0,
         },
         {
            key: 'blend',
            label: 'Blend',
            type: 'select',
            defaultValue: 'max',
            options: [
               { label: 'Max', value: 'max' },
               { label: 'Screen', value: 'screen' },
               { label: 'Add', value: 'add' },
            ],
         },
      ],
   },
   {
      id: 'halftone',
      name: 'Halftone',
      params: [
         {
            key: 'scale',
            label: 'Scale',
            type: 'range',
            min: 2,
            max: 40,
            step: 0.5,
            defaultValue: 8,
         },
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 90,
            step: 1,
            defaultValue: 15,
         },
         {
            key: 'contrast',
            label: 'Contrast',
            type: 'range',
            min: 0.5,
            max: 2,
            step: 0.05,
            defaultValue: 1,
         },
         {
            key: 'mode',
            label: 'Mode',
            type: 'select',
            defaultValue: 'dots',
            options: [
               { label: 'Dots', value: 'dots' },
               { label: 'Dither', value: 'dither' },
               { label: 'Lines', value: 'lines' },
            ],
         },
         { key: 'invert', label: 'Invert', type: 'checkbox', defaultValue: 0 },
      ],
   },
   {
      id: 'swirl',
      name: 'Swirl',
      params: [
         {
            key: 'angle',
            label: 'Angle',
            type: 'range',
            min: 0,
            max: 720,
            step: 1,
            defaultValue: 180,
         },
         {
            key: 'radius',
            label: 'Radius',
            type: 'range',
            min: 0.1,
            max: 1.5,
            step: 0.01,
            defaultValue: 0.75,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0,
            max: 5,
            step: 0.1,
            defaultValue: 0.5,
         },
      ],
   },
   {
      id: 'ripple',
      name: 'Ripple',
      params: [
         {
            key: 'amount',
            label: 'Amount',
            type: 'range',
            min: 0,
            max:100,
            step: 0.5,
            defaultValue: 10,
         },
         {
            key: 'frequency',
            label: 'Frequency',
            type: 'range',
            min: 1,
            max: 30,
            step: 0.5,
            defaultValue: 8,
         },
         {
            key: 'speed',
            label: 'Speed',
            type: 'range',
            min: 0.1,
            max: 5,
            step: 0.1,
            defaultValue: 1,
         },
      ],
   },
   {
      id: 'blur',
      name: 'Blur',
      params: [
         {
            key: 'radius',
            label: 'Radius',
            type: 'range',
            min: 0,
            max: 20,
            step: 0.5,
            defaultValue: 5,
         },
      ],
   },
   {
      id: 'ascii',
      name: 'ASCII',
      params: [
         {
            key: 'size',
            label: 'Cell Size',
            type: 'range',
            min: 4,
            max: 40,
            step: 1,
            defaultValue: 9,
            // Small cells are where the detail lives — give them slider width.
            curve: 2,
            moshMax: 22,
         },
         {
            key: 'aspect',
            label: 'Cell Aspect',
            type: 'range',
            min: 1,
            max: 2.5,
            step: 0.05,
            defaultValue: 2,
         },
         {
            key: 'charset',
            label: 'Character Set',
            type: 'select',
            defaultValue: 'classic',
            options: ASCII_CHARSETS.map(({ label, value }) => ({ label, value })),
         },
         {
            key: 'edges',
            label: 'Edges',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.55,
         },
         {
            key: 'contrast',
            label: 'Contrast',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'color',
            label: 'Color',
            type: 'select',
            defaultValue: 'color',
            options: [
               { label: 'Color', value: 'color' },
               { label: 'Green', value: 'green' },
               { label: 'Amber', value: 'amber' },
               { label: 'White', value: 'white' },
               { label: 'Quantized', value: 'quantized' },
            ],
         },
         {
            key: 'background',
            label: 'Background',
            type: 'select',
            defaultValue: 'black',
            options: [
               { label: 'Black', value: 'black' },
               { label: 'Tint', value: 'tint' },
               { label: 'Image', value: 'image' },
            ],
         },
      ],
   },
   {
      id: 'radial-blur',
      name: 'Radial Blur',
      params: [
         {
            key: 'strength',
            label: 'Strength',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
      ],
   },
   {
      id: 'liquid-light',
      name: 'Liquid Light',
      params: [
         {
            key: 'scale',
            label: 'Cell Size',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.55,
         },
         {
            key: 'flow',
            label: 'Flow',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
         {
            key: 'refraction',
            label: 'Refraction',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
            moshMin: 0.25,
         },
         {
            key: 'dispersion',
            label: 'Dispersion',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
         },
      ],
   },
   {
      id: 'petri',
      name: 'Petri',
      params: [
         {
            key: 'reaction',
            label: 'Reaction',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'drift',
            label: 'Drift',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.72,
         },
         {
            key: 'scale',
            label: 'Pattern Size',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.3,
         },
         {
            key: 'takeover',
            label: 'Takeover',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
            moshMax: 0.8,
         },
      ],
   },
   {
      id: 'flow-contours',
      name: 'Flow Contours',
      params: [
         {
            key: 'bands',
            label: 'Bands',
            type: 'range',
            min: 2,
            max: 24,
            step: 1,
            defaultValue: 8,
         },
         {
            key: 'flow',
            label: 'Flow',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.45,
         },
         {
            key: 'cycle',
            label: 'Hue Cycle',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'sheen',
            label: 'Sheen',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.4,
         },
      ],
   },
   {
      id: 'tracking',
      name: 'Tracking',
      params: [
         {
            key: 'count',
            label: 'Targets',
            type: 'range',
            min: 1,
            max: 12,
            step: 1,
            defaultValue: 5,
            moshMax: 8,
         },
         {
            key: 'sensitivity',
            label: 'Sensitivity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'size',
            label: 'Box Size',
            type: 'range',
            min: 0.03,
            max: 0.3,
            step: 0.005,
            defaultValue: 0.12,
         },
         {
            key: 'thickness',
            label: 'Line Width',
            type: 'range',
            min: 1,
            max: 3,
            step: 0.5,
            defaultValue: 2,
         },
         {
            key: 'opacity',
            label: 'Opacity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
            moshMin: 0.6,
         },
         {
            key: 'color',
            label: 'Color',
            type: 'select',
            defaultValue: 'white',
            options: [
               { label: 'White', value: 'white' },
               { label: 'Black', value: 'black' },
            ],
         },
      ],
   },
   {
      id: 'caption',
      name: 'Caption',
      moshable: false,
      params: [
         {
            key: 'text',
            label: 'Text',
            type: 'text',
            defaultValue: '',
            maxLength: 120,
            placeholder: 'Caption text',
         },
         {
            key: 'x',
            label: 'Position X',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'y',
            label: 'Position Y',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 0.5,
         },
         {
            key: 'size',
            label: 'Size',
            type: 'range',
            min: 0.02,
            max: 0.5,
            step: 0.005,
            defaultValue: 0.1,
         },
         {
            key: 'font',
            label: 'Font',
            type: 'select',
            defaultValue: FONT_OPTIONS[0].family,
            options: FONT_OPTIONS.map((f) => ({
               label: f.label,
               value: f.family,
            })),
         },
         {
            key: 'align',
            label: 'Align',
            type: 'select',
            defaultValue: 'center',
            options: [
               { label: 'Left', value: 'left' },
               { label: 'Center', value: 'center' },
               { label: 'Right', value: 'right' },
            ],
         },
         {
            key: 'color',
            label: 'Color',
            type: 'color',
            defaultValue: '#ffffff',
         },
         {
            key: 'outline',
            label: 'Outline',
            type: 'checkbox',
            defaultValue: 1,
         },
         {
            key: 'outlineColor',
            label: 'Outline Color',
            type: 'color',
            defaultValue: '#000000',
            visibleWhen: (v) => v.outline === 1,
         },
         {
            key: 'outlineWidth',
            label: 'Outline Width',
            type: 'range',
            min: 0,
            max: 8,
            step: 0.5,
            defaultValue: 2,
            visibleWhen: (v) => v.outline === 1,
         },
         {
            key: 'opacity',
            label: 'Opacity',
            type: 'range',
            min: 0,
            max: 1,
            step: 0.01,
            defaultValue: 1,
         },
         {
            key: 'blendMode',
            label: 'Blend Mode',
            type: 'select',
            defaultValue: 'normal',
            options: [
               { label: 'Normal', value: 'normal' },
               { label: 'Multiply', value: 'multiply' },
               { label: 'Screen', value: 'screen' },
               { label: 'Overlay', value: 'overlay' },
               { label: 'Add', value: 'add' },
               { label: 'Subtract', value: 'subtract' },
               { label: 'Difference', value: 'difference' },
               { label: 'Exclusion', value: 'exclusion' },
            ],
         },
      ],
   },
];
